version: "3"

services:
  db:
    image: mysql:5.7 #windows
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: instagram
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always

  web:
    container_name: web
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      mysql_host: db
    restart: always
    volumes:
      - app:/app

volumes:
  dbdata:
  app:
